//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1008 版自动生成。
// 
#pragma warning disable 1591

namespace RemotableHGU_PBoss_Adapter.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NMExternalOtherUtilServiceSoap11Binding", Namespace="http://ws.gxlu.com")]
    public partial class NMExternalOtherUtilService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback returnMakeDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback drawbackResourceConfigGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncGISONUInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncCustomerAndResourceInfo4ZiGuanOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryInternetByCustomerCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback qureyCountyFaultOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOrderInfoGroupWebGisOperationCompleted;
        
        private System.Threading.SendOrPostCallback unifiedLoginAuthenticationOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryGPONDeviceInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryActLanPortInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryAccessModeOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncCustomerInfoForInterNetOperationCompleted;
        
        private System.Threading.SendOrPostCallback querySiteNameByPFOperationCompleted;
        
        private System.Threading.SendOrPostCallback archiveResourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback feedBackResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncTTAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryCommunityFaultStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryAccountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NMExternalOtherUtilService() {
            this.Url = global::RemotableHGU_PBoss_Adapter.Properties.Settings.Default.RemotableHGU_PBoss_Adapter_WebReference_NMExternalOtherUtilService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event returnMakeDataCompletedEventHandler returnMakeDataCompleted;
        
        /// <remarks/>
        public event drawbackResourceConfigGroupCompletedEventHandler drawbackResourceConfigGroupCompleted;
        
        /// <remarks/>
        public event syncGISONUInfoCompletedEventHandler syncGISONUInfoCompleted;
        
        /// <remarks/>
        public event syncCustomerAndResourceInfo4ZiGuanCompletedEventHandler syncCustomerAndResourceInfo4ZiGuanCompleted;
        
        /// <remarks/>
        public event queryInternetByCustomerCodeCompletedEventHandler queryInternetByCustomerCodeCompleted;
        
        /// <remarks/>
        public event qureyCountyFaultCompletedEventHandler qureyCountyFaultCompleted;
        
        /// <remarks/>
        public event getOrderInfoGroupWebGisCompletedEventHandler getOrderInfoGroupWebGisCompleted;
        
        /// <remarks/>
        public event unifiedLoginAuthenticationCompletedEventHandler unifiedLoginAuthenticationCompleted;
        
        /// <remarks/>
        public event queryGPONDeviceInfoCompletedEventHandler queryGPONDeviceInfoCompleted;
        
        /// <remarks/>
        public event queryActLanPortInfoCompletedEventHandler queryActLanPortInfoCompleted;
        
        /// <remarks/>
        public event queryAccessModeCompletedEventHandler queryAccessModeCompleted;
        
        /// <remarks/>
        public event syncCustomerInfoForInterNetCompletedEventHandler syncCustomerInfoForInterNetCompleted;
        
        /// <remarks/>
        public event querySiteNameByPFCompletedEventHandler querySiteNameByPFCompleted;
        
        /// <remarks/>
        public event archiveResourceCompletedEventHandler archiveResourceCompleted;
        
        /// <remarks/>
        public event feedBackResultCompletedEventHandler feedBackResultCompleted;
        
        /// <remarks/>
        public event syncTTAddressCompletedEventHandler syncTTAddressCompleted;
        
        /// <remarks/>
        public event queryCommunityFaultStatusCompletedEventHandler queryCommunityFaultStatusCompleted;
        
        /// <remarks/>
        public event queryAccountCompletedEventHandler queryAccountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:returnMakeData", RequestNamespace="http://ws.gxlu.com/xsd", ResponseNamespace="http://ws.gxlu.com/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string returnMakeData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string request) {
            object[] results = this.Invoke("returnMakeData", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void returnMakeDataAsync(string request) {
            this.returnMakeDataAsync(request, null);
        }
        
        /// <remarks/>
        public void returnMakeDataAsync(string request, object userState) {
            if ((this.returnMakeDataOperationCompleted == null)) {
                this.returnMakeDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreturnMakeDataOperationCompleted);
            }
            this.InvokeAsync("returnMakeData", new object[] {
                        request}, this.returnMakeDataOperationCompleted, userState);
        }
        
        private void OnreturnMakeDataOperationCompleted(object arg) {
            if ((this.returnMakeDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.returnMakeDataCompleted(this, new returnMakeDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:drawbackResourceConfigGroup", RequestNamespace="http://ws.gxlu.com/xsd", ResponseNamespace="http://ws.gxlu.com/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string drawbackResourceConfigGroup([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string requestXML) {
            object[] results = this.Invoke("drawbackResourceConfigGroup", new object[] {
                        requestXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void drawbackResourceConfigGroupAsync(string requestXML) {
            this.drawbackResourceConfigGroupAsync(requestXML, null);
        }
        
        /// <remarks/>
        public void drawbackResourceConfigGroupAsync(string requestXML, object userState) {
            if ((this.drawbackResourceConfigGroupOperationCompleted == null)) {
                this.drawbackResourceConfigGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OndrawbackResourceConfigGroupOperationCompleted);
            }
            this.InvokeAsync("drawbackResourceConfigGroup", new object[] {
                        requestXML}, this.drawbackResourceConfigGroupOperationCompleted, userState);
        }
        
        private void OndrawbackResourceConfigGroupOperationCompleted(object arg) {
            if ((this.drawbackResourceConfigGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.drawbackResourceConfigGroupCompleted(this, new drawbackResourceConfigGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncGISONUInfo", RequestNamespace="http://ws.gxlu.com/xsd", ResponseNamespace="http://ws.gxlu.com/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void syncGISONUInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string onuname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string onu, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string model, long portid, [System.Xml.Serialization.XmlIgnoreAttribute()] bool portidSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tempOnu, out int @return, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool returnSpecified) {
            object[] results = this.Invoke("syncGISONUInfo", new object[] {
                        onuname,
                        sn,
                        onu,
                        model,
                        portid,
                        portidSpecified,
                        tempOnu});
            @return = ((int)(results[0]));
            returnSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void syncGISONUInfoAsync(string onuname, string sn, string onu, string model, long portid, bool portidSpecified, string tempOnu) {
            this.syncGISONUInfoAsync(onuname, sn, onu, model, portid, portidSpecified, tempOnu, null);
        }
        
        /// <remarks/>
        public void syncGISONUInfoAsync(string onuname, string sn, string onu, string model, long portid, bool portidSpecified, string tempOnu, object userState) {
            if ((this.syncGISONUInfoOperationCompleted == null)) {
                this.syncGISONUInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncGISONUInfoOperationCompleted);
            }
            this.InvokeAsync("syncGISONUInfo", new object[] {
                        onuname,
                        sn,
                        onu,
                        model,
                        portid,
                        portidSpecified,
                        tempOnu}, this.syncGISONUInfoOperationCompleted, userState);
        }
        
        private void OnsyncGISONUInfoOperationCompleted(object arg) {
            if ((this.syncGISONUInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncGISONUInfoCompleted(this, new syncGISONUInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncCustomerAndResourceInfo4ZiGuan", RequestNamespace="http://ws.gxlu.com/xsd", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void syncCustomerAndResourceInfo4ZiGuan([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productInstanceCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productType, int operation, [System.Xml.Serialization.XmlIgnoreAttribute()] bool operationSpecified) {
            this.Invoke("syncCustomerAndResourceInfo4ZiGuan", new object[] {
                        productInstanceCode,
                        productType,
                        operation,
                        operationSpecified});
        }
        
        /// <remarks/>
        public void syncCustomerAndResourceInfo4ZiGuanAsync(string productInstanceCode, string productType, int operation, bool operationSpecified) {
            this.syncCustomerAndResourceInfo4ZiGuanAsync(productInstanceCode, productType, operation, operationSpecified, null);
        }
        
        /// <remarks/>
        public void syncCustomerAndResourceInfo4ZiGuanAsync(string productInstanceCode, string productType, int operation, bool operationSpecified, object userState) {
            if ((this.syncCustomerAndResourceInfo4ZiGuanOperationCompleted == null)) {
                this.syncCustomerAndResourceInfo4ZiGuanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncCustomerAndResourceInfo4ZiGuanOperationCompleted);
            }
            this.InvokeAsync("syncCustomerAndResourceInfo4ZiGuan", new object[] {
                        productInstanceCode,
                        productType,
                        operation,
                        operationSpecified}, this.syncCustomerAndResourceInfo4ZiGuanOperationCompleted, userState);
        }
        
        private void OnsyncCustomerAndResourceInfo4ZiGuanOperationCompleted(object arg) {
            if ((this.syncCustomerAndResourceInfo4ZiGuanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncCustomerAndResourceInfo4ZiGuanCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryInternetByCustomerCode", RequestNamespace="http://ws.gxlu.com/xsd", ResponseNamespace="http://ws.gxlu.com/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string queryInternetByCustomerCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string request) {
            object[] results = this.Invoke("queryInternetByCustomerCode", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryInternetByCustomerCodeAsync(string request) {
            this.queryInternetByCustomerCodeAsync(request, null);
        }
        
        /// <remarks/>
        public void queryInternetByCustomerCodeAsync(string request, object userState) {
            if ((this.queryInternetByCustomerCodeOperationCompleted == null)) {
                this.queryInternetByCustomerCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryInternetByCustomerCodeOperationCompleted);
            }
            this.InvokeAsync("queryInternetByCustomerCode", new object[] {
                        request}, this.queryInternetByCustomerCodeOperationCompleted, userState);
        }
        
        private void OnqueryInternetByCustomerCodeOperationCompleted(object arg) {
            if ((this.queryInternetByCustomerCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryInternetByCustomerCodeCompleted(this, new queryInternetByCustomerCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:qureyCountyFault", RequestNamespace="http://ws.gxlu.com/xsd", ResponseNamespace="http://ws.gxlu.com/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string qureyCountyFault([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string request) {
            object[] results = this.Invoke("qureyCountyFault", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void qureyCountyFaultAsync(string request) {
            this.qureyCountyFaultAsync(request, null);
        }
        
        /// <remarks/>
        public void qureyCountyFaultAsync(string request, object userState) {
            if ((this.qureyCountyFaultOperationCompleted == null)) {
                this.qureyCountyFaultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqureyCountyFaultOperationCompleted);
            }
            this.InvokeAsync("qureyCountyFault", new object[] {
                        request}, this.qureyCountyFaultOperationCompleted, userState);
        }
        
        private void OnqureyCountyFaultOperationCompleted(object arg) {
            if ((this.qureyCountyFaultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.qureyCountyFaultCompleted(this, new qureyCountyFaultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getOrderInfoGroupWebGis", RequestNamespace="http://ws.gxlu.com/xsd", ResponseNamespace="http://ws.gxlu.com/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string getOrderInfoGroupWebGis([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string requestXML) {
            object[] results = this.Invoke("getOrderInfoGroupWebGis", new object[] {
                        requestXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getOrderInfoGroupWebGisAsync(string requestXML) {
            this.getOrderInfoGroupWebGisAsync(requestXML, null);
        }
        
        /// <remarks/>
        public void getOrderInfoGroupWebGisAsync(string requestXML, object userState) {
            if ((this.getOrderInfoGroupWebGisOperationCompleted == null)) {
                this.getOrderInfoGroupWebGisOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOrderInfoGroupWebGisOperationCompleted);
            }
            this.InvokeAsync("getOrderInfoGroupWebGis", new object[] {
                        requestXML}, this.getOrderInfoGroupWebGisOperationCompleted, userState);
        }
        
        private void OngetOrderInfoGroupWebGisOperationCompleted(object arg) {
            if ((this.getOrderInfoGroupWebGisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOrderInfoGroupWebGisCompleted(this, new getOrderInfoGroupWebGisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:unifiedLoginAuthentication", RequestNamespace="http://ws.gxlu.com/xsd", ResponseNamespace="http://ws.gxlu.com/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string unifiedLoginAuthentication([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string requestXML) {
            object[] results = this.Invoke("unifiedLoginAuthentication", new object[] {
                        requestXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void unifiedLoginAuthenticationAsync(string requestXML) {
            this.unifiedLoginAuthenticationAsync(requestXML, null);
        }
        
        /// <remarks/>
        public void unifiedLoginAuthenticationAsync(string requestXML, object userState) {
            if ((this.unifiedLoginAuthenticationOperationCompleted == null)) {
                this.unifiedLoginAuthenticationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunifiedLoginAuthenticationOperationCompleted);
            }
            this.InvokeAsync("unifiedLoginAuthentication", new object[] {
                        requestXML}, this.unifiedLoginAuthenticationOperationCompleted, userState);
        }
        
        private void OnunifiedLoginAuthenticationOperationCompleted(object arg) {
            if ((this.unifiedLoginAuthenticationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.unifiedLoginAuthenticationCompleted(this, new unifiedLoginAuthenticationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryGPONDeviceInfo", RequestNamespace="http://ws.gxlu.com/xsd", ResponseNamespace="http://ws.gxlu.com/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string queryGPONDeviceInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string request) {
            object[] results = this.Invoke("queryGPONDeviceInfo", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryGPONDeviceInfoAsync(string request) {
            this.queryGPONDeviceInfoAsync(request, null);
        }
        
        /// <remarks/>
        public void queryGPONDeviceInfoAsync(string request, object userState) {
            if ((this.queryGPONDeviceInfoOperationCompleted == null)) {
                this.queryGPONDeviceInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryGPONDeviceInfoOperationCompleted);
            }
            this.InvokeAsync("queryGPONDeviceInfo", new object[] {
                        request}, this.queryGPONDeviceInfoOperationCompleted, userState);
        }
        
        private void OnqueryGPONDeviceInfoOperationCompleted(object arg) {
            if ((this.queryGPONDeviceInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryGPONDeviceInfoCompleted(this, new queryGPONDeviceInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryActLanPortInfo", RequestNamespace="http://ws.gxlu.com/xsd", ResponseNamespace="http://ws.gxlu.com/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string queryActLanPortInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string request) {
            object[] results = this.Invoke("queryActLanPortInfo", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryActLanPortInfoAsync(string request) {
            this.queryActLanPortInfoAsync(request, null);
        }
        
        /// <remarks/>
        public void queryActLanPortInfoAsync(string request, object userState) {
            if ((this.queryActLanPortInfoOperationCompleted == null)) {
                this.queryActLanPortInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryActLanPortInfoOperationCompleted);
            }
            this.InvokeAsync("queryActLanPortInfo", new object[] {
                        request}, this.queryActLanPortInfoOperationCompleted, userState);
        }
        
        private void OnqueryActLanPortInfoOperationCompleted(object arg) {
            if ((this.queryActLanPortInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryActLanPortInfoCompleted(this, new queryActLanPortInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryAccessMode", RequestNamespace="http://ws.gxlu.com/xsd", ResponseNamespace="http://ws.gxlu.com/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string queryAccessMode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string request) {
            object[] results = this.Invoke("queryAccessMode", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryAccessModeAsync(string request) {
            this.queryAccessModeAsync(request, null);
        }
        
        /// <remarks/>
        public void queryAccessModeAsync(string request, object userState) {
            if ((this.queryAccessModeOperationCompleted == null)) {
                this.queryAccessModeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryAccessModeOperationCompleted);
            }
            this.InvokeAsync("queryAccessMode", new object[] {
                        request}, this.queryAccessModeOperationCompleted, userState);
        }
        
        private void OnqueryAccessModeOperationCompleted(object arg) {
            if ((this.queryAccessModeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryAccessModeCompleted(this, new queryAccessModeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncCustomerInfoForInterNet", RequestNamespace="http://ws.gxlu.com/xsd", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void syncCustomerInfoForInterNet([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productInstanceCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productType, int operation, [System.Xml.Serialization.XmlIgnoreAttribute()] bool operationSpecified) {
            this.Invoke("syncCustomerInfoForInterNet", new object[] {
                        productInstanceCode,
                        productType,
                        operation,
                        operationSpecified});
        }
        
        /// <remarks/>
        public void syncCustomerInfoForInterNetAsync(string productInstanceCode, string productType, int operation, bool operationSpecified) {
            this.syncCustomerInfoForInterNetAsync(productInstanceCode, productType, operation, operationSpecified, null);
        }
        
        /// <remarks/>
        public void syncCustomerInfoForInterNetAsync(string productInstanceCode, string productType, int operation, bool operationSpecified, object userState) {
            if ((this.syncCustomerInfoForInterNetOperationCompleted == null)) {
                this.syncCustomerInfoForInterNetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncCustomerInfoForInterNetOperationCompleted);
            }
            this.InvokeAsync("syncCustomerInfoForInterNet", new object[] {
                        productInstanceCode,
                        productType,
                        operation,
                        operationSpecified}, this.syncCustomerInfoForInterNetOperationCompleted, userState);
        }
        
        private void OnsyncCustomerInfoForInterNetOperationCompleted(object arg) {
            if ((this.syncCustomerInfoForInterNetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncCustomerInfoForInterNetCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:querySiteNameByPF", RequestNamespace="http://ws.gxlu.com/xsd", ResponseNamespace="http://ws.gxlu.com/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string querySiteNameByPF([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string requestXML) {
            object[] results = this.Invoke("querySiteNameByPF", new object[] {
                        requestXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void querySiteNameByPFAsync(string requestXML) {
            this.querySiteNameByPFAsync(requestXML, null);
        }
        
        /// <remarks/>
        public void querySiteNameByPFAsync(string requestXML, object userState) {
            if ((this.querySiteNameByPFOperationCompleted == null)) {
                this.querySiteNameByPFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnquerySiteNameByPFOperationCompleted);
            }
            this.InvokeAsync("querySiteNameByPF", new object[] {
                        requestXML}, this.querySiteNameByPFOperationCompleted, userState);
        }
        
        private void OnquerySiteNameByPFOperationCompleted(object arg) {
            if ((this.querySiteNameByPFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.querySiteNameByPFCompleted(this, new querySiteNameByPFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:archiveResource", RequestNamespace="http://ws.gxlu.com/xsd", ResponseNamespace="http://ws.gxlu.com/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string archiveResource([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string requestXML) {
            object[] results = this.Invoke("archiveResource", new object[] {
                        requestXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void archiveResourceAsync(string requestXML) {
            this.archiveResourceAsync(requestXML, null);
        }
        
        /// <remarks/>
        public void archiveResourceAsync(string requestXML, object userState) {
            if ((this.archiveResourceOperationCompleted == null)) {
                this.archiveResourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnarchiveResourceOperationCompleted);
            }
            this.InvokeAsync("archiveResource", new object[] {
                        requestXML}, this.archiveResourceOperationCompleted, userState);
        }
        
        private void OnarchiveResourceOperationCompleted(object arg) {
            if ((this.archiveResourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.archiveResourceCompleted(this, new archiveResourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:feedBackResult", RequestNamespace="http://ws.gxlu.com/xsd", ResponseNamespace="http://ws.gxlu.com/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string feedBackResult([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string request) {
            object[] results = this.Invoke("feedBackResult", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void feedBackResultAsync(string request) {
            this.feedBackResultAsync(request, null);
        }
        
        /// <remarks/>
        public void feedBackResultAsync(string request, object userState) {
            if ((this.feedBackResultOperationCompleted == null)) {
                this.feedBackResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfeedBackResultOperationCompleted);
            }
            this.InvokeAsync("feedBackResult", new object[] {
                        request}, this.feedBackResultOperationCompleted, userState);
        }
        
        private void OnfeedBackResultOperationCompleted(object arg) {
            if ((this.feedBackResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.feedBackResultCompleted(this, new feedBackResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:syncTTAddress", RequestNamespace="http://ws.gxlu.com/xsd", ResponseNamespace="http://ws.gxlu.com/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string syncTTAddress([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string request) {
            object[] results = this.Invoke("syncTTAddress", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncTTAddressAsync(string request) {
            this.syncTTAddressAsync(request, null);
        }
        
        /// <remarks/>
        public void syncTTAddressAsync(string request, object userState) {
            if ((this.syncTTAddressOperationCompleted == null)) {
                this.syncTTAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncTTAddressOperationCompleted);
            }
            this.InvokeAsync("syncTTAddress", new object[] {
                        request}, this.syncTTAddressOperationCompleted, userState);
        }
        
        private void OnsyncTTAddressOperationCompleted(object arg) {
            if ((this.syncTTAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncTTAddressCompleted(this, new syncTTAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryCommunityFaultStatus", RequestNamespace="http://ws.gxlu.com/xsd", ResponseNamespace="http://ws.gxlu.com/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string queryCommunityFaultStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string request) {
            object[] results = this.Invoke("queryCommunityFaultStatus", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryCommunityFaultStatusAsync(string request) {
            this.queryCommunityFaultStatusAsync(request, null);
        }
        
        /// <remarks/>
        public void queryCommunityFaultStatusAsync(string request, object userState) {
            if ((this.queryCommunityFaultStatusOperationCompleted == null)) {
                this.queryCommunityFaultStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryCommunityFaultStatusOperationCompleted);
            }
            this.InvokeAsync("queryCommunityFaultStatus", new object[] {
                        request}, this.queryCommunityFaultStatusOperationCompleted, userState);
        }
        
        private void OnqueryCommunityFaultStatusOperationCompleted(object arg) {
            if ((this.queryCommunityFaultStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryCommunityFaultStatusCompleted(this, new queryCommunityFaultStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryAccount", RequestNamespace="http://ws.gxlu.com/xsd", ResponseNamespace="http://ws.gxlu.com/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string queryAccount([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string request) {
            object[] results = this.Invoke("queryAccount", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryAccountAsync(string request) {
            this.queryAccountAsync(request, null);
        }
        
        /// <remarks/>
        public void queryAccountAsync(string request, object userState) {
            if ((this.queryAccountOperationCompleted == null)) {
                this.queryAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryAccountOperationCompleted);
            }
            this.InvokeAsync("queryAccount", new object[] {
                        request}, this.queryAccountOperationCompleted, userState);
        }
        
        private void OnqueryAccountOperationCompleted(object arg) {
            if ((this.queryAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryAccountCompleted(this, new queryAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void returnMakeDataCompletedEventHandler(object sender, returnMakeDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class returnMakeDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal returnMakeDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void drawbackResourceConfigGroupCompletedEventHandler(object sender, drawbackResourceConfigGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class drawbackResourceConfigGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal drawbackResourceConfigGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void syncGISONUInfoCompletedEventHandler(object sender, syncGISONUInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncGISONUInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncGISONUInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int @return {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool returnSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void syncCustomerAndResourceInfo4ZiGuanCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void queryInternetByCustomerCodeCompletedEventHandler(object sender, queryInternetByCustomerCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryInternetByCustomerCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryInternetByCustomerCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void qureyCountyFaultCompletedEventHandler(object sender, qureyCountyFaultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class qureyCountyFaultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal qureyCountyFaultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getOrderInfoGroupWebGisCompletedEventHandler(object sender, getOrderInfoGroupWebGisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOrderInfoGroupWebGisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOrderInfoGroupWebGisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void unifiedLoginAuthenticationCompletedEventHandler(object sender, unifiedLoginAuthenticationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class unifiedLoginAuthenticationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal unifiedLoginAuthenticationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void queryGPONDeviceInfoCompletedEventHandler(object sender, queryGPONDeviceInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryGPONDeviceInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryGPONDeviceInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void queryActLanPortInfoCompletedEventHandler(object sender, queryActLanPortInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryActLanPortInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryActLanPortInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void queryAccessModeCompletedEventHandler(object sender, queryAccessModeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryAccessModeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryAccessModeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void syncCustomerInfoForInterNetCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void querySiteNameByPFCompletedEventHandler(object sender, querySiteNameByPFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class querySiteNameByPFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal querySiteNameByPFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void archiveResourceCompletedEventHandler(object sender, archiveResourceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class archiveResourceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal archiveResourceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void feedBackResultCompletedEventHandler(object sender, feedBackResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class feedBackResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal feedBackResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void syncTTAddressCompletedEventHandler(object sender, syncTTAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncTTAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncTTAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void queryCommunityFaultStatusCompletedEventHandler(object sender, queryCommunityFaultStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryCommunityFaultStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryCommunityFaultStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void queryAccountCompletedEventHandler(object sender, queryAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591